### ISSUE TITLE
Question: which pins necessary?

### ISSUE THREAD

**Issue by sheldonh** [dramaturg/docker-debian-systemd#5]
I'm trying to use your work as a basis for a container that's used in an integration test. It has very specific Debian needs (Jessie and systemd and a host of other things).

I ran into trouble with your APT preferences: they prevented selection of nginx and passenger from Phusion's repo.

Are you able to say which packages needed to be pinned for systemd to start up? When I completely removed your APT preferences, systemd didn't start up, so obviously some of them are required. :)

**Comment by dramaturg** [comment]
From the top of my head you need at least systemd itself from the backports.
(This is surely not true anymore for the current stretch-based config but it'll be for the jessie config used before bec770206f48b64c3bbdc9ce037dfa27931ff6ff)

You could try removing the pinning and installing stuff from backports from your Dockerfile like this:
`RUN apt-get install -t jessie-backports initscripts libsystemd0 libudev1 systemd sysvinit-utils udev`
(Untested shot in the dark)

Let me know how it goes! :smiley:

**Comment by sheldonh** [comment]
Thanks for the guidance.

Under pressure, I gave up and ran docker with `--privileged`, at which point your Dockerfile works for jessie without backports or testing. This is just for an integration test, so `--privileged` is a small price to pay. :)
